### ISSUE TITLE
"Module Error Level" has incorrect range for N163 instrument wave count.

### ISSUE THREAD

**Issue by eulyderg** [Gumball2415/j0CC-FamiTracker#121]
In Dn-FamiTracker 0.4.0.1, when the module error checking level is set to "Official" (depicted below), **valid** N163 modules with more than 16 waves in an instrument are flagged as invalid.
![image](https://user-images.githubusercontent.com/31630195/149636452-fbafe3d5-1eaf-4763-a918-01f7d3dc4621.png)

This range should be 1 to 64, but it checks 1 to 16.
This error occurs on a valid module.
![image](https://user-images.githubusercontent.com/31630195/149636465-31faae64-bda6-42f8-b363-469b15e05f1e.png)

**Comment by eulyderg** [comment]
nevermind it is vanilla compatability

**Comment by pinobatch** [comment]
It might be wise to change "the official build" to "FamiTracker 0.4.6" in this form to help users understand what it does.
