### ISSUE TITLE
What's the difference between Debug and Release?

### ISSUE THREAD

**Issue by lts20050703** [Gumball2415/j0CC-FamiTracker#132]
What's the difference betwen Debug and Release? When I download the zip file from the latest release and extract it I see two folder, debug and release
Which one should I use?
P/s I think you should release both as a separate download, if that's possible :)

**Comment by Gumball2415** [comment]
The release builds has its code and instructions trimmed and optimized for performance, while the debug builds print extra internal debugging info. It has more error checking, slow, and less optimized code to help debuggers print program state.

tl;dr: Release builds for regular use, Debug builds for debugging crashes, developer use, etc.

I'll have them as a separate download in the next release, thank you for commenting on that.
