### ISSUE TITLE
[Issue Reporting/Feature Request] Sunsoft 5B Wxx command

### ISSUE THREAD

**Issue by Abstract64** [Gumball2415/j0CC-FamiTracker#160]
Regarding the title, I have experienced issues with the Wxx command on 5B, which was used to control the noise pitch. Some of the issues I have encountered were:

1. The command does not work when you export the .nsf
2. The command doesn't work globally as muting the channel that's controlling the noise pitch would also disable the command, making other channel's noise default to pitch 0 (W00). 

Could this behavior be fixed both inside the program and also the export itself?

(FYI, the square mode macro in the instrument settings does control the noise pitch properly, makes the pitch global and works on the .nsf export. So i just wonder why this doesn't happen with the Wxx command.)

And as a feature request, is it possible to make the Wxx value carry on to the next note without it resetting to W00? So that I don't have to spam it like in the picture. (I was using speed 1 lol)
![unknown-11](https://user-images.githubusercontent.com/103553186/190561914-ce43caf7-f48d-421e-bfcc-3053133c5e5a.png)

**Comment by Gumball2415** [comment]
There was an earlier fix in j0CC regarding [S5B non-noise instruments overwriting noise period](https://github.com/nyanpasu64/j0CC-FamiTracker/pull/96), hence the current in-tracker state of Wxx. And this earlier fix in j0CC regarding the [S5B NSF driver skips last entry in noise sequence](https://github.com/nyanpasu64/j0CC-FamiTracker/pull/105) has disabled Wxx in the NSF driver as an ad-hoc solution. I will look into this soon.

**Comment by Gumball2415** [comment]
> And as a feature request, is it possible to make the Wxx value carry on to the next note without it resetting to W00? So that I don't have to spam it like in the picture. (I was using speed 1 lol)

Wxx already carries its value similar to most effects commands. You might be overwriting it with other instruments/channel effects due to the 5B sound chip only having a single noise channel shared among all 3 tone channels.
