### ISSUE TITLE
Add Missing Commands to Text import and export

### ISSUE THREAD

**Issue by TheRealQuantam** [Gumball2415/j0CC-FamiTracker#161]
PLAYBACKRATE, TUNING, DETUNE, GROOVE, and USEGROOVE appear to be implemented* but are not documented in the help.

*PLAYBACKRATE appears to only be partially implemented. It's read but not written by the exporter (the line is commented out and is only partially written, seemingly started but never finished).

**Comment by Gumball2415** [comment]
in FamiTracker 0.5.0 beta, the playback rate system was overhauled, adding NSF play speed and vblank-timed engine speed, in addition to the usual engine speed module property. I assume HertzDevil added these options in anticipation for the release of FamiTracker 0.5.0.
