### ISSUE TITLE
Command-line operations do not behave like a command-line program

### ISSUE THREAD

**Issue by TheRealQuantam** [Gumball2415/j0CC-FamiTracker#168]
Several oddities exist with the Dn-FT CLI where it acts very different than a normal CLI app.

- Dn-FT doesn't properly use stdout/stderr. This can be proven by the fact that the output streams cannot be redirected but will always print out.
- Some errors produce message boxes rather than printing to stdout/stderr. E.g. I got this when I accidentally passed the FT directory as the input filename and got a message box saying that the file could not be opened.
- It requires user input to complete ("press enter") -- NOT ACTUALLY TRUE

**Comment by Gumball2415** [comment]
Dn-FamiTracker is an MFC app, not a CLI app. Therefore, there's bound to be some incongruent capabilities compared to typical CLI applications.

There are some functions that allow MFC apps to write to commandline, but they are quite limited.

**Comment by TheRealQuantam** [comment]
Some Google results on the topic that will hopefully work:
- Re stdout and stderr: https://stackoverflow.com/a/45642269/3574457 / https://www.tillett.info/2013/05/13/how-to-create-a-windows-program-that-works-as-both-as-a-gui-and-console-application/
- Re: Requiring pressing enter: https://devblogs.microsoft.com/oldnewthing/20160125-00/?p=92922

**Comment by TheRealQuantam** [comment]
Okay, finally rolled up my sleeves to try it myself. It appears the issue with redirection is more complicated than I understood. I just posted [this question](https://learn.microsoft.com/answers/questions/1155425/using-stdinouterr-from-a-gui-with-redirection-supp.html) with what I've learned and hopefully somebody in MS will be able to give a way to do it. There IS a way of working around it (use fdopen to open the redirected handle rather than using stdout/stderr), but if there's a way to do it properly I'd sure like to know it.

Also, I now see that it never actually required you to press enter. The message saying to do so was either because the person who wrote it didn't understand how the console launches GUI apps or because the end user was not expected to understand. Explanation: the command line waits for CLI apps to finish, but not GUI apps. By the time FT has attached to the console and printed out its stuff, the command line has already returned to and printed out the command prompt, and the text FT writes comes AFTER the command prompt. But the command line is still AT the command prompt; all pressing enter does is make it print the command prompt again (same as pressing enter at the command prompt).

**Comment by TheRealQuantam** [comment]
Okay, I think I've got a fix for the redirection thing. It took me a bit to figure out why the method that worked in my test app wasn't working in FT. What is the reason CFamiTrackerApp::InitInstance calls ExitProcess(0) when command line execution fails rather than returns FALSE like all the other failure conditions?

**Comment by Gumball2415** [comment]
Fixed by #181.
