### ISSUE TITLE
Cannot open my dnm file.

### ISSUE THREAD

**Issue by wkt1227** [Gumball2415/j0CC-FamiTracker#171]
Suddenly I can't open [my dnm file](https://drive.google.com/file/d/1KSYUDoVRjBotlHUR_8JLexL99oXyRGa1/view?usp=sharing).
I need a solution.
The error message is as follows

>Sequence loop point out of range: expected [-1,-1], got 0
At instrument 03,
At address 0x444 in INSTRUMENTS block,
address 0x54D in file

**Comment by Gumball2415** [comment]
This seems to be an issue with module corruption, which has been historically very difficult to trace.
The error message says what went wrong upon loading the module, so i changed the int32 at that address to be -1.
Side note, currently Dn-FT does not support loading modules with unicode characters, so i renamed the module to use ascii characters.
[torigo no machi fix.zip](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/files/10216828/torigo.no.machi.fix.zip)
