### ISSUE TITLE
Specific effects changing type when older modules are saved in 0.5.0.0

### ISSUE THREAD

**Issue by Threxx11** [Gumball2415/j0CC-FamiTracker#184]
Transferring my post in the famitracker.org discord...

> okay, this is pretty consistently reproducible
> if you make a module with a Txy effect, save the module, and reopen it, the Txy effects in the module will all be changed to Ixx effects. as you can imagine this can severely break modules reliant on the transpose effect and is not ideal.
> 
> the steps i took to reproduce it:
> 1. make a new module. i tested forward porting modules from 0CC and new modules made in Dn, it seems to occur no matter what
> 2. add a Txy effect to any channel.
> 3. save the module
> 3. close the tracker, and then reopen the same module. the effects will now be changed to the wrong type as stated previously.

It also seems that other effects may also transform when the module is updated, though I have not observed these directly myself, I will note them:
-`0xx` effects may be replaced with `Hxx` effects when a module is saved and loaded.
-`Lxx` effects may be replaced with `Wxx` effects when a module is saved and loaded, **but only on the DPCM channel.**

Attached are 3 modules demonstrating the Txy effect replacement phenomena.
[test.zip](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/files/10449918/test.zip)

**Comment by Gumball2415** [comment]
what version are these test modules saved in?
