### ISSUE TITLE
Weird sound plays with N163?

### ISSUE THREAD

**Issue by jadasse** [Gumball2415/j0CC-FamiTracker#185]
Every time I open a document with N163 enabled, it makes a loud sawtooth wave noise from low to high with noise added to it for a few seconds, and it scares me every time it plays. Why does it happen? How can I disable it? Is it a bug? I'm still scared.

**Comment by jadasse** [comment]
https://user-images.githubusercontent.com/71288109/213364588-1c3a6da8-d9c3-45a8-8a83-cceeea32765b.mp4

the audio

**Comment by Gumball2415** [comment]
Is it on a specific module, or is it on any module with N163?

**Comment by jadasse** [comment]
> Is it on a specific module, or is it on any module with N163?

It's on any module.

**Comment by Gumball2415** [comment]
can you provide a video recording, with register view enabled? i can't seem to replicate this bug

**Comment by jadasse** [comment]
https://user-images.githubusercontent.com/71288109/213860734-be5926ba-f23f-409d-bb6f-cc2bbcecedca.mp4

**Comment by Gumball2415** [comment]
so this sawtooth sweep happens when you lose focus of a new module with N163 enabled?

**Comment by jadasse** [comment]
> so this sawtooth sweep happens when you lose focus of a new module with N163 enabled?

No, it just happens.

**Comment by jadasse** [comment]
I know what happened; I set the lowpass cutoff filter for the N163 to the maximum by spamming "9", which plays the noise and makes the N163 not play.
