### ISSUE TITLE
Unable to open certain .ftm files

### ISSUE THREAD

**Issue by sunshinespecialist** [Gumball2415/j0CC-FamiTracker#192]
https://web.archive.org/web/20170130070756/http://www.fodxm.co.uk/fod_coffeezonesources.zip
Attempting to open 12_laser.ftm gives the following error:
```
Sequence loop point out of range: expected [-1, -1], got 0
At instrument 1A,
At address 0x1DB6 in INSTRUMENTS block,
address 0x1EBF in file
```

**Comment by Gumball2415** [comment]
this error appears to occur all the way back to 0CC-FT 0.3.14.5

**Comment by Gumball2415** [comment]
it appears that some of these modules contain corrupted data.
my recommendation is to set Module Error Level to "None", then open the module. note that this mode can load corrupt and invalid module data.
