### ISSUE TITLE
Missing JSON export

### ISSUE THREAD

**Issue by nstbayless** [Gumball2415/j0CC-FamiTracker#197]
Unless I'm mistaken, Dn-Famitracker does not have JSON export, which is a feature in 0CC-Famitracker. Here are side-by-side screenshots of Dn-Famitracker and 0CC-Famitracker:

![image](https://user-images.githubusercontent.com/7698597/226197212-a0b92526-ec02-4994-a3bb-117ead507ef9.png)

JSON export is a very handy feature because it's easily parsable by scripts. This facilitates, for example, converting a famitracker module into an engine-specific format.

**Comment by Gumball2415** [comment]
Dn-FT is based on 0CC version 0.3.14.5. the last release of 0CC (version 0.3.15.3) has left the codebase in a somewhat incompatible state. more effort will be required to port JSON export into Dn-FT.

**Comment by nstbayless** [comment]
I could work on a pull request that offers support for this feature. I'd like to confirm first, however, that this won't be rejected simply because the JSON export feature is for some reason undesirable.

**Comment by Gumball2415** [comment]
i wouldn't mind feature parity with the last known 0CC dev build really, so i'm not against such a PR
