### ISSUE TITLE
Are channels other than apu1 and apu2 being quiet in multichip modules intended?

### ISSUE THREAD

**Issue by trashbinenthusiast** [Gumball2415/j0CC-FamiTracker#213]
This is what i have to do to make all channels sound even: https://i.imgur.com/8GHmxRn.png
This was the problem when 0.5.0.0 came out, and it still is, hardware mixing box doesn't fix anything. It has been reported before on FT discord, and multiple people have said the same as well. 0.4.0.1 does not have this problem.

**Comment by N-SPC700** [comment]
It's been a while. But I recall the "quieting" of multiple channels with multiple chips is automatically done to prevent clipping. I personally don't agree with the feature, and it makes mixing absolutely irritating, but if I recall correctly, that's why it was done.

**Comment by Gumball2415** [comment]
the channels are attenuated depending on the amount of chips enabled. this behavior has been unchanged since FT 0.4.6

**Comment by Gumball2415** [comment]
can you provide .wav exports for comparison? also, what build are you using?

**Comment by trashbinenthusiast** [comment]
> can you provide .wav exports for comparison? also, what build are you using?

I've used 0cc 0.3.15.3 in the past and I've been using Dn-FT 0.4.0.1 for a while. They do not have this problem. Also, i was the first user to point this out many months ago on ft discord, but nothing has changed since then at all. Perhaps i'll stick to 0.4.0.1 then.

**Comment by trashbinenthusiast** [comment]
> It's been a while. But I recall the "quieting" of multiple channels with multiple chips is automatically done to prevent clipping. I personally don't agree with the feature, and it makes mixing absolutely irritating, but if I recall correctly, that's why it was done.

I really don't get it. Why even have multichip support if you cripple that functionality by doing that? There should be a togglable option instead of forcing it like that. I'm still using 0.4.0.1 because of it.

**Comment by Gumball2415** [comment]
this functionality is as old as multichip itself, if you don't like it, go back to vanilla

**Comment by nyanpasu64** [comment]
Can you supply a test module, which sounds different in different versions of Dn?

**Comment by trashbinenthusiast** [comment]
> this functionality is as old as multichip itself, if you don't like it, go back to vanilla

I've been using famitracker for more than 10 years, and not at a single point ever had i encountered such extreme case of channel imbalance *until* the last version of Dn-FT. Yes, the channels do get quieter the more chips you add, but it's the first time I'm seeing 2a03 being so much louder than the rest. It seems you either misunderstand me or just don't care about this issue at all.

**Comment by trashbinenthusiast** [comment]
> Can you supply a test module, which sounds different in different versions of Dn?

Literally every single vrc6 + mmc5 module i have.

**Comment by trashbinenthusiast** [comment]
I will continue this discussion on discord, it's easier to post examples in it.
