### ISSUE TITLE
Editing ftm files from the old Famitracker

### ISSUE THREAD

**Issue by barrett-ok** [Gumball2415/j0CC-FamiTracker#228]
Hi!
This might be a dumb question, but this is my first time using Dn-Famitracker. Is it normal that, if I open an old FTM file from the original program, I should be unable to edit the file? It loads and plays just fine! Do I have to conver the FTM into something Dn can edit first before I can do anything?
Thank you for your time, I really appreciate it.
barrett

**Comment by Gumball2415** [comment]
Dn-FamiTracker is forwards-compatible with modules saved in FamiTracker and 0CC-FamiTracker. note that .dnm files may not be backwards compatible with 0CC-FamiTracker and FamiTracker as of version 0.5.0.0

**Comment by barrett-ok** [comment]
That makes me wonder what is preventing me from editing my module.Sent from my iPhoneOn Jul 19, 2023, at 5:38 AM, Persune ***@***.***> wrote:﻿
Dn-FamiTracker is forwards-compatible with modules saved in FamiTracker and 0CC-FamiTracker. note that .dnm files may not be backwards compatible with 0CC-FamiTracker and FamiTracker as of version 0.5.0.0

**Comment by Gumball2415** [comment]
have you enabled edit/record mode in the tracker?

**Comment by barrett-ok** [comment]
Like by pressing spacebar? The same as in og famitracker???Sent from my iPhoneOn Jul 19, 2023, at 9:34 AM, Persune ***@***.***> wrote:﻿
have you enabled edit/record mode in the tracker?
