### ISSUE TITLE
version check break. (was the number intentional?, was this error an elaborate joke?)

### ISSUE THREAD

**Issue by yoopgim** [Gumball2415/j0CC-FamiTracker#229]
first thing i see when i open up the latest version:
![Screenshot 2023-07-29 123701](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/51343338/eee581d3-eaa4-46fb-b290-4879ff5c579c)

1, how did this happen?
2, how did the person who updated it know in advance how it was going to break it?
3, was that number a coincidence or on purpose?

**Comment by Gumball2415** [comment]
1. see #212 
2. i did not know that GitHub was redirecting links under my userspace into D.P.C.M. until i released version 0.5.0.1
3. the number is on purpose, i needed a version number higher than any foreseeable current release versions.
