### ISSUE TITLE
Apple Silicon support...?

### ISSUE THREAD

**Issue by Sourdface** [Gumball2415/j0CC-FamiTracker#234]
I know this is crazy, but what would it take to port this to run natively on MacOS with Apple Silicon? The closest I've been able to get is to install Windows 11 inside Parallels Desktop, but their pricing plan is impractical, and even then, the app doesn't run 100% smoothly. ~~Trying to use Wine cases causes major slowdown, timing issues, and audio distortion to the point where the app is almost unusable.~~ _Actually, Wine can't run it at all, though CrossOver can run it in a near-unusable state._

**Comment by Gumball2415** [comment]
https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/issues/88#issuecomment-932929975

**Comment by bradharms** [comment]
That was 2 years ago. Any changes since then?

**Comment by Sourdface** [comment]
> [#88 (comment)](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/issues/88#issuecomment-932929975)

That comment was made 2 years ago. Have there been any updates since then? Where can I find the discussion?

**Comment by Gumball2415** [comment]
no updates since, and discussion was in ft.o Discord iirc.
the main crux of porting is:
- fix thread issues
- detangling UI and logic
- porting GUI to cross-platform GUI
- porting logic to use cross-platform libraries

which each individual one is, mind you, a herculean task

**Comment by Sourdface** [comment]
Understood. Thank you for the feedback.

**Comment by zeta0134** [comment]
fwiw, **wine crossover** is able to successfully boot and run Dn-FamiTracker on Apple Silicon, at least on my mac mini with its stock M1. I remember having to do some additional finangling and I'm afraid I don't remember the details (I'm on holiday) but give `brew install crossover` a try as a starting point.

FamiTracker is ultimately a Windows program and fairly entrenched in the Win32 GUI framework, so a native port is rather unlikely. Wine is your best bet.

**Comment by Sourdface** [comment]
> fwiw, **wine crossover** is able to successfully boot and run Dn-FamiTracker on Apple Silicon, at least on my mac mini with its stock M1. I remember having to do some additional finangling and I'm afraid I don't remember the details (I'm on holiday) but give `brew install crossover` a try as a starting point.
> 
> FamiTracker is ultimately a Windows program and fairly entrenched in the Win32 GUI framework, so a native port is rather unlikely. Wine is your best bet.

That's strange. I tried CrossOver before, and it barely worked at all, the lag and overall sound quality was so bad it was unusable. But I just tried it again from Brew and now it works just fine.

**Comment by BleuBleu** [comment]
FamiStudio runs as a native ARM app on MacOS and supports retina display. Note that audio will get some improvement on MacOS in 4.2.0 as well (will detect device changes, better BT headphones support, latency reduction, etc).

Sorry to inject, feel free to delete this comment if you think its inappropriate to suggest other apps. 

-Mat

**Comment by Sourdface** [comment]
I just tested this, and [Wine 9.0 (Stable)](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0) apparently runs Dn FamiTracker flawlessly on Apple M2 Pro, thanks to WoW64. Playback was buttery smooth and I didn't notice any visual or audio distortions.
