### ISSUE TITLE
New *.nsf-export algorithm question/bug?

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Gumball2415/j0CC-FamiTracker#242]
Hi! I need to ask you about new NSF-export algorithm, maybe you can help me.

Classic versions of Famitracker and 0cc-Famitracker generate standart *.nsf-file, NTSC-headered. 
If you play it on emulator in PAL or Dendy mode - tempo will slowing down, and this is absolutely normal.

But new version of DN-famitracker does something strange.
It also generates standard.nsf-file, NTSC headered, but it:
 
- plays same tempo on NTSC/PAL/Dendy (Mesen)
- have old-style behavior described above (nestopia, fceux)
- crackling on puNES emulator at PAL/Dendy.

Maybe you know what's really happened in the new NSF-export algorhitms or it's general DN-Famitracker bug?
[nsf_test.zip](https://github.com/punesemu/puNES/files/13403860/nsf_test.zip)

**Comment by Gumball2415** [comment]
as of this time of writing, no version of FT or any FT fork supports Dendy mode.

can you clarify whether your exported NSFs are NTSC-headered or Dual region headered? FT has options to export NTSC, PAL, or both, with the NSF player discerning which one to use.

**Comment by eugene-s-nesdev** [comment]
I've generated NSFs from FTM-file (look at archive) manually, it's NTSC headered.

**Comment by Gumball2415** [comment]
> plays same tempo on NTSC/PAL/Dendy (Mesen)

can you also clarify on this? on my build of Mesen2, the tempo and pitch slows down as expected.
are you referring to the compiled ROMs, or the compiled NSFs?

**Comment by Gumball2415** [comment]
... i see the problem with NSF export on PAL

![image](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/54422576/5f3998ed-af0b-4c8f-8beb-9284e8ca1922)

see issue #223 for details.

**Comment by eugene-s-nesdev** [comment]
> can you also clarify on this? on my build of Mesen2, the tempo and pitch slows down as expected.
> are you referring to the compiled ROMs, or the compiled NSFs?

I have lastest Mesen2 autobuild.
Compiled NES ROMs plays right way (slowing down pitch/tempo at PAL and Dendy, and different DPCM-LUTs in true-PAL)
Compiled NSFs plays same tempo in all 3 regions, and it looks like bug.
Classic versions of Famitracker and 0cc-Famitracker generates NSF "right" way

**Comment by eugene-s-nesdev** [comment]
https://github.com/punesemu/puNES/issues/346
puNES crackling issues

**Comment by Gumball2415** [comment]
yes, it's an issue with the PAL play rate not being set correctly, as seen in #223.
any emulator implementing a Dendy NSF player follows this:

> If the Dendy speed is omitted, any Dendy playback should use the PAL speed. (If the PAL speed is omitted, its default rate should be used.) Use with the [regn](https://www.nesdev.org/wiki/NSFe#regn) chunk to enable Dendy playback.
https://www.nesdev.org/wiki/NSFe#RATE

This means that PAL _and_ Dendy NSFs play at the erroneous 60Hz rate that Dn-FT exports.

This is a planned fix in PR #214.

**Comment by Gumball2415** [comment]
as for puNES, i don't think it's within Dn-FT's jurisdiction to fix an external emulator's implementation.

**Comment by eugene-s-nesdev** [comment]
> This is a planned fix in PR #214

Thank you
