### ISSUE TITLE
Som .ftm modules from 2014 can't be opened

### ISSUE THREAD

**Issue by freq-mod** [Gumball2415/j0CC-FamiTracker#269]
[FTMS.zip](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/files/14917629/FTMS.zip) - these modules (made by Fearofdark) dont open in the newest DN-Famitracker release, with note out of bounds error. These modules arent corrupted, as, somehow, they open in Furnace (yes, support for ftms and related got added)

**Comment by Gumball2415** [comment]
all but `12_laser.ftm` is openable in Dn-FT under Default module error level.
all of them has corrupt module data which is somehow ignored in vanilla.

Dn-FT has stricter error checking by default. if you wish to open them anyway, try setting your Module Error Level to None in configuration settings.

see #215 for another issue which encounters hidden corrupt pattern data.
