### ISSUE TITLE
Program UI fails update after launch

### ISSUE THREAD

**Issue by aquamarine-axo** [Gumball2415/j0CC-FamiTracker#273]
https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/78063037/dbdda177-d1a0-4b9f-9be5-3a08ccbd85aa

Video description: Dn-FamiTracker is launched. UI doesn't update after program is launched, however the program itself appears to operate fine.

To reproduce:
- Launch Dn-FamiTracker
- Attempt to interact with the UI

Expected behavior: Program's UI updates after user sends an input to the program

System information:
- Arch Linux x86_64, all packages latest
- wine-staging 9.8-1
- wine-mono 9.1.0
- wine-gecko 2.47.4
- Dn-FamiTracker release build 0.5.0.2, downloaded from Releases section

**Comment by nyanpasu64** [comment]
probably a wine bug, possibly related to a tiling manager. reminds me of https://bugs.winehq.org/show_bug.cgi?id=52903 but that was reported fixed in wine 8.0-rc3.

does resizing (shrinking, or expanding) the window redraw it partially or fully?

**Comment by aquamarine-axo** [comment]
Partially. It appears that only the first frame was drawn when the application was opened, no other frames get painted. Anywhere where the window is resized either cuts part of the UI off or leaves empty black space where it used to be.

**Comment by nyanpasu64** [comment]
Are you running on X11 or Wayland? What WM/compositor are you using? Wine probably only runs on XWayland right now.

I haven't tried debugging yet but this is useful background information to reproduce or locate the cause of not redrawing.

**Comment by aquamarine-axo** [comment]
Wayland with Sway

**Comment by aquamarine-axo** [comment]
Running on an Intel integrated GPU with the Mesa drivers, if it helps

**Comment by nyanpasu64** [comment]
not the same setup, but i don't get rendering failures on 0.5.0.2 with arch linux, wine-9.10 (not staging), kde x11 or wayland, on amdgpu. not sure what to do next, and i can't test other setups at the moment. have you tried x11 or other desktop environments, maybe wine non-staging?

**Comment by aquamarine-axo** [comment]
After further testing, the issue appears to be specific to Sway. Dn-Famitracker works fine under my existing config under latest KDE on Wayland. Could potentially be a WINE issue rather than a WM issue however.

**Comment by aquamarine-axo** [comment]
The issue was with Sway. Closing...

**Comment by nyanpasu64** [comment]
- does it occur with other programs like winecfg or openmpt?
- is it worth filing a bug with either wine, xwayland, or sway about the windows not properly repainting?

**Comment by aquamarine-axo** [comment]
- Yes, it occurred with all WINE programs
- The bug is likely with WINE. I'm not sure however, since I've since searched for the problem and many people have had (and posted somewhere about) this issue. An issue was already made 3 years ago in Sway's repo and was closed, without any comments from the dev.
