### ISSUE TITLE
N163 waveforms are reversed on visualizer

### ISSUE THREAD

**Issue by Kyuchumimo** [Gumball2415/j0CC-FamiTracker#91]
![screen](https://user-images.githubusercontent.com/74131798/135729601-773fa3d1-2491-4e4b-8abf-de606868bb26.png)
![screen2](https://user-images.githubusercontent.com/74131798/135729602-dbc772bf-3ace-4a74-9d40-3952bbe23ae8.png)

This does not happen in FamiTracker v0.4.6 or 0CC-FamiTracker 0.3.15.3, only in j0CC-FamiTracker 0.6.3 or Dn-FamiTracker (which is based on j0CC-Famitracker 0.6.3, so this problem has always been present in Dn-Famitracker)

Using Wine 6.0.1 on Lubuntu 21.04

**Comment by Gumball2415** [comment]
After running some crosschecking with nsfplay, Dn-FamiTracker, and my Mappy Kids cartridge, it seems that this is correct and hardware accurate behavior.

### nsfplay's N163 emulation in relation to hardware (top is nsfplay, bottom is famicom hardware)
- notice the direction of the saw base matching hardware
- note that the phase of the hardware recording is globally inverted, so i had to revert it for easier comparison

![image](https://user-images.githubusercontent.com/54422576/135763964-7c1e2379-4bd4-49e6-80f9-1147400b7add.png)

### Dn-FT's N163 emulation in relation to nsfplay: (top is Dn-FT, bottom is nsfplay)

![image](https://user-images.githubusercontent.com/54422576/135763578-4c60c810-7bdf-4f6a-9316-8f7b21d056d0.png)


[test recordings used](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/files/7274133/expansion.audio.phase.test.zip). note that famicom hardware audio phase is overall inverted, but in relation to 2a03, it's still correct.
